spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zhkh_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master-employee.yaml
server:
  port: 8082
