spring:
  cloud:
    gateway:
      routes:
        - id: apartment-service
          uri: http://localhost:8080
          predicates:
            - Path=api/apartments/**

        - id: building-service
          uri: http://localhost:8081
          predicates:
            - Path=api/buildings/**

        - id: resident-service
          uri: http://localhost:8082
          predicates:
            - Path=api/residents/**
server:
  port: 8083