server:
  port: ${GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: apartment-service
          uri: ${services.apartment.url}
          predicates:
            - Path=/api/apartments/**

        - id: building-service
          uri: ${services.building.url}
          predicates:
            - Path=/api/buildings/**

        - id: counterparty-service
          uri: ${services.counterparty.url}
          predicates:
            - Path=/api/counterparties/**

        - id: employee-service
          uri: ${services.employee.url}
          predicates:
            - Path=/api/employees/**

        - id: office-service
          uri: ${services.office.url}
          predicates:
            - Path=/offices/**

        - id: registration-service
          uri: ${services.registration.url}
          predicates:
            - Path=/api/registration/**

        - id: request-service
          uri: ${services.request.url}
          predicates:
            - Path=/api/requests/**

        - id: resident-service
          uri: ${services.resident.url}
          predicates:
            - Path=/api/residents/**

        - id: review-service
          uri: ${services.review.url}
          predicates:
            - Path=/api/reviews/**

        - id: service-catalog-service
          uri: ${services.service-catalog.url}
          predicates:
            - Path=/api/services/**
            -
        - id: user-service
          uri: ${services.user.url}
          predicates:
            - Path=/api/users/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

services:
  apartment:
    url: ${APARTMENT_SERVICE_URL}
  building:
    url: ${BUILDING_SERVICE_URL}
  counterparty:
    url: ${COUNTERPARTY_SERVICE_URL}
  employee:
    url: ${EMPLOYEE_SERVICE_URL}
  office:
    url: ${OFFICE_SERVICE_URL}
  registration:
    url: ${REGISTRATION_SERVICE_URL}
  request:
    url: ${REQUEST_SERVICE_URL}
  resident:
    url: ${RESIDENT_SERVICE_URL}
  review:
    url: ${REVIEW_SERVICE_URL}
  service-catalog:
    url: ${SERVICE_CATALOG_SERVICE_URL}
  user:
    url: ${USER_SERVICE_URL}


logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
